(cl:defpackage ardrone_command-msg
  (:use )
  (:export
   "<SERIALIZED_ARDRONE_COMMAND_PART>"
   "SERIALIZED_ARDRONE_COMMAND_PART"
   "<COMMAND_STATUS_INFO>"
   "COMMAND_STATUS_INFO"
   "<ALTITUDE_CONTROL_STATE>"
   "ALTITUDE_CONTROL_STATE"
   "<QR_CODE_STATE_INFO>"
   "QR_CODE_STATE_INFO"
   "<SERIALIZED_ARDRONE_COMMAND>"
   "SERIALIZED_ARDRONE_COMMAND"
   "<QR_GO_TO_POINT_CONTROL_INFO>"
   "QR_GO_TO_POINT_CONTROL_INFO"
   "<QR_ORIENTATION_CONTROL_INFO>"
   "QR_ORIENTATION_CONTROL_INFO"
  ))

