// Generated by gencpp from file ardrone_command/qr_orientation_control_info.msg
// DO NOT EDIT!


#ifndef ARDRONE_COMMAND_MESSAGE_QR_ORIENTATION_CONTROL_INFO_H
#define ARDRONE_COMMAND_MESSAGE_QR_ORIENTATION_CONTROL_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_command
{
template <class ContainerAllocator>
struct qr_orientation_control_info_
{
  typedef qr_orientation_control_info_<ContainerAllocator> Type;

  qr_orientation_control_info_()
    : time_stamp()
    , z_rotation_throttle(0.0)  {
    }
  qr_orientation_control_info_(const ContainerAllocator& _alloc)
    : time_stamp()
    , z_rotation_throttle(0.0)  {
    }



   typedef ros::Time _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef double _z_rotation_throttle_type;
  _z_rotation_throttle_type z_rotation_throttle;




  typedef boost::shared_ptr< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> const> ConstPtr;

}; // struct qr_orientation_control_info_

typedef ::ardrone_command::qr_orientation_control_info_<std::allocator<void> > qr_orientation_control_info;

typedef boost::shared_ptr< ::ardrone_command::qr_orientation_control_info > qr_orientation_control_infoPtr;
typedef boost::shared_ptr< ::ardrone_command::qr_orientation_control_info const> qr_orientation_control_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ardrone_command': ['/home/ghost/catkin_ws/src/ardrone_command/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd437299f6524928ef23e8c13d9f30d9";
  }

  static const char* value(const ::ardrone_command::qr_orientation_control_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd437299f6524928ULL;
  static const uint64_t static_value2 = 0xef23e8c13d9f30d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_command/qr_orientation_control_info";
  }

  static const char* value(const ::ardrone_command::qr_orientation_control_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#This message is use to reveal what the QR code orientation control is doing with the angular velocity\n\
\n\
time time_stamp\n\
\n\
float64 z_rotation_throttle #P control, rotate left if target is left, etc (-QRCodePoint[0]/fabs(QRCodePoint[2]))\n\
";
  }

  static const char* value(const ::ardrone_command::qr_orientation_control_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.z_rotation_throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct qr_orientation_control_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_command::qr_orientation_control_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_command::qr_orientation_control_info_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "z_rotation_throttle: ";
    Printer<double>::stream(s, indent + "  ", v.z_rotation_throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_COMMAND_MESSAGE_QR_ORIENTATION_CONTROL_INFO_H
