"""autogenerated by genpy from ardrone_command/altitude_control_state.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class altitude_control_state(genpy.Message):
  _md5sum = "5a10456794d65dd23bebefb4d2ed1033"
  _type = "ardrone_command/altitude_control_state"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#altitude control command info

time time_stamp
float64 target_altitude #Altitude to try to achieve in mm
float64 current_p_term #(targetAltitude - fabs(altitude))
float64 current_i_term  #targetAltitudeITerm = targetAltitudeITerm + pTerm


"""
  __slots__ = ['time_stamp','target_altitude','current_p_term','current_i_term']
  _slot_types = ['time','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time_stamp,target_altitude,current_p_term,current_i_term

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(altitude_control_state, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.target_altitude is None:
        self.target_altitude = 0.
      if self.current_p_term is None:
        self.current_p_term = 0.
      if self.current_i_term is None:
        self.current_i_term = 0.
    else:
      self.time_stamp = genpy.Time()
      self.target_altitude = 0.
      self.current_p_term = 0.
      self.current_i_term = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I3d.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.target_altitude, _x.current_p_term, _x.current_i_term))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.target_altitude, _x.current_p_term, _x.current_i_term,) = _struct_2I3d.unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I3d.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.target_altitude, _x.current_p_term, _x.current_i_term))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.target_altitude, _x.current_p_term, _x.current_i_term,) = _struct_2I3d.unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I3d = struct.Struct("<2I3d")
