"""autogenerated by genpy from ardrone_command/command_status_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ardrone_command.msg
import genpy

class command_status_info(genpy.Message):
  _md5sum = "fda30b7f63165f1d42bf9428eb25149d"
  _type = "ardrone_command/command_status_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time time_stamp
uint32 commandNumber #Internal count of the command (should go up by 1 for each command completed or skipped)
#Command that the library is currently working on
serialized_ardrone_command command 

================================================================================
MSG: ardrone_command/serialized_ardrone_command
#ROS message format doesn't support recursive definitions (a message type cannot contain more messages of the same type), so commands will have to be decomposed when they are serialized and will not be exactly the same on the other side
serialized_ardrone_command_part command
serialized_ardrone_command_part[] subcommands 


================================================================================
MSG: ardrone_command/serialized_ardrone_command_part
uint32 type
string[] strings
float64[] doubles
int64[] integers
uint32[] flightAnimations
uint32[] ledAnimations

"""
  __slots__ = ['time_stamp','commandNumber','command']
  _slot_types = ['time','uint32','ardrone_command/serialized_ardrone_command']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time_stamp,commandNumber,command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(command_status_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.commandNumber is None:
        self.commandNumber = 0
      if self.command is None:
        self.command = ardrone_command.msg.serialized_ardrone_command()
    else:
      self.time_stamp = genpy.Time()
      self.commandNumber = 0
      self.command = ardrone_command.msg.serialized_ardrone_command()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4I.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.commandNumber, _x.command.command.type))
      length = len(self.command.command.strings)
      buff.write(_struct_I.pack(length))
      for val1 in self.command.command.strings:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.command.command.doubles)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.command.command.doubles))
      length = len(self.command.command.integers)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.command.command.integers))
      length = len(self.command.command.flightAnimations)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.command.command.flightAnimations))
      length = len(self.command.command.ledAnimations)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.command.command.ledAnimations))
      length = len(self.command.subcommands)
      buff.write(_struct_I.pack(length))
      for val1 in self.command.subcommands:
        buff.write(_struct_I.pack(val1.type))
        length = len(val1.strings)
        buff.write(_struct_I.pack(length))
        for val2 in val1.strings:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          if python3:
            buff.write(struct.pack('<I%sB'%length, length, *val2))
          else:
            buff.write(struct.pack('<I%ss'%length, length, val2))
        length = len(val1.doubles)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.pack(pattern, *val1.doubles))
        length = len(val1.integers)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(struct.pack(pattern, *val1.integers))
        length = len(val1.flightAnimations)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.pack(pattern, *val1.flightAnimations))
        length = len(val1.ledAnimations)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.pack(pattern, *val1.ledAnimations))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.command is None:
        self.command = ardrone_command.msg.serialized_ardrone_command()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.commandNumber, _x.command.command.type,) = _struct_4I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command.command.strings = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.command.command.strings.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.doubles = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.integers = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.flightAnimations = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.ledAnimations = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command.subcommands = []
      for i in range(0, length):
        val1 = ardrone_command.msg.serialized_ardrone_command_part()
        start = end
        end += 4
        (val1.type,) = _struct_I.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.strings = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8')
          else:
            val2 = str[start:end]
          val1.strings.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.doubles = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.integers = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        end += struct.calcsize(pattern)
        val1.flightAnimations = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        end += struct.calcsize(pattern)
        val1.ledAnimations = struct.unpack(pattern, str[start:end])
        self.command.subcommands.append(val1)
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4I.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.commandNumber, _x.command.command.type))
      length = len(self.command.command.strings)
      buff.write(_struct_I.pack(length))
      for val1 in self.command.command.strings:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.command.command.doubles)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.command.command.doubles.tostring())
      length = len(self.command.command.integers)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.command.command.integers.tostring())
      length = len(self.command.command.flightAnimations)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.command.command.flightAnimations.tostring())
      length = len(self.command.command.ledAnimations)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.command.command.ledAnimations.tostring())
      length = len(self.command.subcommands)
      buff.write(_struct_I.pack(length))
      for val1 in self.command.subcommands:
        buff.write(_struct_I.pack(val1.type))
        length = len(val1.strings)
        buff.write(_struct_I.pack(length))
        for val2 in val1.strings:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          if python3:
            buff.write(struct.pack('<I%sB'%length, length, *val2))
          else:
            buff.write(struct.pack('<I%ss'%length, length, val2))
        length = len(val1.doubles)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.doubles.tostring())
        length = len(val1.integers)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(val1.integers.tostring())
        length = len(val1.flightAnimations)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.flightAnimations.tostring())
        length = len(val1.ledAnimations)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.ledAnimations.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.command is None:
        self.command = ardrone_command.msg.serialized_ardrone_command()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.commandNumber, _x.command.command.type,) = _struct_4I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command.command.strings = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.command.command.strings.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.doubles = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.integers = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.flightAnimations = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.command.command.ledAnimations = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command.subcommands = []
      for i in range(0, length):
        val1 = ardrone_command.msg.serialized_ardrone_command_part()
        start = end
        end += 4
        (val1.type,) = _struct_I.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.strings = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8')
          else:
            val2 = str[start:end]
          val1.strings.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.doubles = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.integers = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        end += struct.calcsize(pattern)
        val1.flightAnimations = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        end += struct.calcsize(pattern)
        val1.ledAnimations = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        self.command.subcommands.append(val1)
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4I = struct.Struct("<4I")
