"""autogenerated by genpy from ardrone_command/qr_orientation_control_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class qr_orientation_control_info(genpy.Message):
  _md5sum = "cd437299f6524928ef23e8c13d9f30d9"
  _type = "ardrone_command/qr_orientation_control_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#This message is use to reveal what the QR code orientation control is doing with the angular velocity

time time_stamp

float64 z_rotation_throttle #P control, rotate left if target is left, etc (-QRCodePoint[0]/fabs(QRCodePoint[2]))

"""
  __slots__ = ['time_stamp','z_rotation_throttle']
  _slot_types = ['time','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time_stamp,z_rotation_throttle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(qr_orientation_control_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.z_rotation_throttle is None:
        self.z_rotation_throttle = 0.
    else:
      self.time_stamp = genpy.Time()
      self.z_rotation_throttle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Id.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.z_rotation_throttle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.z_rotation_throttle,) = _struct_2Id.unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Id.pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.z_rotation_throttle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.z_rotation_throttle,) = _struct_2Id.unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Id = struct.Struct("<2Id")
